_target_: pipeline.make_custom_pipeline

steps:
    - Scale:
        _target_: custom_preprocess.noop.NoOp
        # params here

    - Transform:
        _target_: custom_preprocess.noop.NoOp

    - Reduce:
        _target_: custom_preprocess.noop.NoOp

    - Select:
        _target_: custom_preprocess.mutual_info.MutualInformation