_target_: pipeline.make_custom_pipeline

steps:
    - SimpleImputer:
        _target_: sklearn.impute.SimpleImputer
        strategy: 'constant'
        fill_value: -1


    - StandardScaler:
        _target_: sklearn.preprocessing.StandardScaler

    - Scale:
        _target_: noop.NoOp
        # params here

    - Transform:
        _target_: noop.NoOp

    - Reduce: # or expand eg PolynomialFeatures
        _target_: noop.NoOp

    - Select:
        _target_: noop.NoOp

    - Model:
        _target_: sklearn.svm.SVC
        kernel: linear
        C: 0.01
        probability: true
        class_weight: balanced #{'0': 1, '1': 2}

    