_target_: pipeline.make_pipeline

steps:
    - Scale:
        _target_: noop.NoOp
        # params here

    - Transform:
        _target_: noop.NoOp

    - Reduce:
        _target_: noop.NoOp

    - Select:
        _target_: noop.NoOp

    - Model:
        _target_: sklearn.linear_model.LogisticRegression
        penalty: l2
        C: 1.0
        solver: lbfgs
        max_iter: 1000