_target_: hydra_sklearn_pipeline.make_pipeline

steps:
    - Scale:
        _target_: noop.NoOp
        # params here

    - Transform:
        _target_: noop.NoOp

    - Reduce: # or expand eg PolynomialFeatures
        _target_: noop.NoOp

    - Select:
        _target_: noop.NoOp

    - Model:
        _target_: sklearn.svm.SVC
        kernel: linear
        C: 0.01
        probability: true
        #class_weight: {'0' : 1, '1' : 2}

    